version: "3"

services:
  kimberly-caravans-app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: kimberly-caravans-app
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
      - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini:delegated
    networks:
      - kimberly-caravans-network
    depends_on:
      - kimberly-caravans-database

  kimberly-caravans-webserver:
    image: nginx:alpine
    container_name: kimberly-caravans-webserver
    ports:
      - "80:80"
    volumes:
      - ./:/var/www:delegated
      - .docker/nginx/conf.d/:/etc/nginx/conf.d:delegated
    networks:
      kimberly-caravans-network:
        aliases:
          - kimberlycaravans.local
    depends_on:
      - kimberly-caravans-app

  kimberly-caravans-database:
    image: mysql:5.7.22
    container_name: kimberly-caravans-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: kimberlycaravans
      MYSQL_PASSWORD: kimberlycaravans
      MYSQL_DATABASE: kimberlycaravans
    volumes:
      - kimberly-caravans-database-data:/var/lib/mysql
      - .docker/mysql/my.cnf:/etc/mysql/my.cnf:delegated
    networks:
      - kimberly-caravans-network

  kimberly-caravans-test-database:
    image: mysql:5.7.22
    container_name: kimberly-caravans-test-database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: kimberlycaravans
      MYSQL_PASSWORD: kimberlycaravans
      MYSQL_DATABASE: kimberlycaravans
    volumes:
      - .docker/mysql/my.cnf:/etc/mysql/my.cnf:delegated
    networks:
      - kimberly-caravans-network

networks:
  kimberly-caravans-network:
    driver: bridge

volumes:
  kimberly-caravans-database-data:
    driver: local
