- name: Deploy Site
  hosts: all
  remote_user: ubuntu

  vars:
    ansistrano_deploy_to: "{{ deploy_path }}"
    ansistrano_version_dir: "releases" # Releases folder name
    ansistrano_current_dir: "current" # Softlink name. You should rarely changed it.
    ansistrano_current_via: "symlink" # Deployment strategy who code should be deployed to current path. Options are symlink or rsync
    ansistrano_keep_releases: 2 # Releases to keep after a new deployment. See "Pruning old releases".
    ansistrano_deploy_via: "git"
    ansistrano_git_repo: git@github.com:clickds/White-Agency-Marquis.git # Location of the git repository
    ansistrano_git_branch: "{{ branch | default('master') }}" # What version of the repository to check out. This can be the full 40-character SHA-1 hash, the literal string HEAD, a branch name, or a tag name
    ansistrano_before_symlink_tasks_file: "{{ playbook_dir }}/tasks/pre-deploy.yml"
    ansistrano_shared_files:
      - .env
    ansistrano_shared_paths:
      - storage/framework/cache
      - storage/framework/sessions
      - storage/framework/views
      - storage/app
      - storage/logs

  roles:
    - role: ansistrano.deploy
