<a href="{{ url('/') }}" class="block p-5 w-full text-center text-2xl mb-2 font-heading text-gray-700 font-bold">
  Marquis Admin
</a>

<a href="{{ url('/') }}" class="mb-2 w-full bg-blue-500 hover:bg-blue-700 text-white text-center py-2 px-4 inline-block">
  View Site
</a>

<form action="{{ route('logout') }}" method="POST">
  @csrf
  <button type="submit" class="w-full bg-red-500 hover:bg-red-700 text-white py-2 px-4 inline-block">Logout</button>
</form>

<div class="mt-5 flex-grow flex flex-col">
  <nav class="flex-1 space-y-1">
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.aliases.index') }}">Aliases</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.articles.index') }}">Articles</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.article-categories.index') }}">Article Categories</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.assets.index') }}">Assets</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.bed-descriptions.index') }}">Bed Descriptions</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.berths.index') }}">Berths</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.brochures.index') }}">Brochures</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.business-areas.index') }}">Business Areas</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.brochure-groups.index') }}">Brochures Groups</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.ctas.index') }}">Call To Actions</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.dealers.index') }}">Dealers</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.email-recipients.index') }}">Email Recipients</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.events.index') }}">Events</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.event-locations.index') }}">Event Locations</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.fieldsets.index') }}">Fieldsets</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.forms.index') }}">Forms</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.image-banners.index') }}">Image Banners</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.layouts.index') }}">Layouts</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.logos.index') }}">Logos</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.manufacturers.index') }}">Manufacturers</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.navigations.index') }}">Navigations</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.pages.index') }}">Pages</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.pop-ups.index') }}">Pop Ups</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.reviews.index') }}">Reviews</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.review-categories.index') }}">Review Categories</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.seats.index') }}">Seats</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.sites.index') }}">Sites</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.site-settings.index') }}">Site Settings</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.special-offers.index') }}">Special Offers</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.stock-search-links.index') }}">Stock Search Ads/Links</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.testimonials.index') }}">Testimonials</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.useful-links.index') }}">Useful Links</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.useful-link-categories.index') }}">Useful Link Categories</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.users.index') }}">Users</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.vacancies.index') }}">Vacancies</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.videos.index') }}">Videos</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.video-banners.index') }}">Video Banners</a>
    <a class="group flex items-center p-3 text-md leading-5 font-medium text-gray-600 border-l-4 border-transparent hover:text-gray-900 hover:bg-white focus:outline-none focus:text-gray-900 focus:bg-white transition ease-in-out duration-150" href="{{ route('admin.video-categories.index') }}">Video Categories</a>
  </nav>
</div>